# Generated by Django 4.2.6 on 2024-02-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0002_alter_users_lastname_alter_users_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="customer_id",
            field=models.CharField(
                default="ABC32324324CDEFGHIJKLMNO32", max_length=25, unique=True
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="profile/avatar.png",
                null=True,
                upload_to="profile/",
            ),
        ),
    ]
