# Generated by Django 4.2.6 on 2024-02-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("market", "0003_users_customer_id_users_phone_alter_users_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="customer_id",
            field=models.CharField(
                blank=True,
                default="ABC32324324CDEFGHIJKLMNO32",
                max_length=25,
                null=True,
                unique=True,
            ),
        ),
    ]
